"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import "./styles.css";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

const navigationLinks = [
  { href: "/login", label: "Login" },
  { href: "/forgot-password", label: "Forgot-Password" },
  { href: "/register", label: "Register" },
];

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body>
        {navigationLinks?.map((link, i) => {
          const isActive =
            pathname === link?.href ||
            (pathname?.startsWith(link?.href) && link.href !== "/");

          console.log(isActive);
          return (
            <Link
              key={i}
              href={link?.href}
              // style={
              //   isActive
              //     ? {
              //         fontWeight: "bold",
              //         marginRight: "12px",
              //       }
              //     : {
              //         color: "blue",
              //         marginRight: "12px",
              //       }
              // }

              className={isActive ? "font-bold mr-4" : "mr-4 text-blue-bold"}
            >
              {link?.label}
            </Link>
          );
        })}

        <main>{children}</main>
        <footer
          style={{
            backgroundColor: "lightblue",
            padding: "20px",
            textAlign: "center",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
