import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Learning NextJs | frame work", // if any doesn't have the title then thin one will render as title of this children
    template: "%s | nextJs", // this will be added with nextJs in all other title of the children
    // absolute:""
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
        <footer
          style={{
            backgroundColor: "lightblue",
            padding: "20px",
            textAlign: "center",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
