export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function PrivateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "20px",
            textAlign: "center",
          }}
        >
          <p>Header</p>
        </header>
        <main>{children}</main>
        <footer
          style={{
            backgroundColor: "lightblue",
            padding: "20px",
            textAlign: "center",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
